name: ModularPluginSystem
version: '1.0'
main: dev.memorydealer.modularpluginsystem.ModularPluginSystem
api-version: '1.21'
author: MemoryDealer
depend: [Citizens]
commands:
  modules:
    description: Open the Module Management GUI
permissions:
  dev.memorydealer.modules:
    default: op
